version: '3.8'

services:
  ignite-node:
    image: apacheignite/ignite:latest
    container_name: ignite-node
    ports:
      - "10800:10800"   # Thin Client
    restart: always
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: test
      POSTGRES_DB: ignite-with-db
    ports:
      - "5432:5432"
